### ISSUE TITLE
Webpack broken on Windows with 1.3.0

### ISSUE THREAD

**Issue by jasonmacdonald** [marko-js/marko-loader#6]
The following line in Index.js is breaking Windows builds in Webpack because window file paths are used. For example 'c:\Users\User\Desktop\somepath\test\index.marko' gets put in and Webpack then sees it as 'c:UsersUserDesktopSomepath\testsrcindex.marko\' and gives an error in the build output of `var e = new Error("Cannot find module "c:UsersUserDesktopSomepath\testsrcindex.marko\""); e.code = 'MODULE_NOT_FOUND';; throw e; }()));`. Reverting back to loader version 1.2.0 and everything works.

Here's the line that is causing the issue from what I can see.
```Javascript
if (!dependency.code) {
      // external file, just require it
      return `require('${dependency.path}');`
 }
```

**Comment by jasonmacdonald** [comment]
Still broken?

**Comment by larixer** [comment]
@jasonmacdonald Please wait a bit, I will check and return to you soon.

**Comment by larixer** [comment]
@jasonmacdonald Will be fixed once the Pull Request https://github.com/marko-js/marko-loader/pull/12 merged
